GRID_WIDTH = 20
GRID_HEIGHT = 20

POPULATION_SIZE = 100
MAX_GENERATIONS = 2000
MUTATION_PROBABILITY = 0.4
CROSSOVER_PROBABILITY = 0.9

CROSSING_REWARD = 15
CROSSING_PENALTY = 15

OVERLAPPING_REWARD = 50
OVERLAPPING_PENALTY = 50

NEIGHBOURS_REWARD = 20
NEIGHBOURS_PENALTY = 20

CONNECTIVITY_REWARD = 50
CONNECTIVITY_PENALTY = 30
